---
Title: "Competition Code"
author: ""
date: "10/27/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(dplyr)
library(caret)
library(ROCR)
library(MLmetrics)
library(mltools)
library(rpart.plot)
```

```{r}
states <- read.csv("data/states_all_2_training.csv", na.strings=c('',NA))
states_dropped <- states %>% drop_na(GRADES_ALL_G)

str(states)

eduID <- states[, c(1)]
View(eduID)
states <- states[, -c(1)]
View(states)

states$STATE <- fct_collapse(states$STATE,
                                      NewEngland = c("CONNECTICUT", "MAINE", "MASSACHUSETTS", "NEW_HAMPSHIRE", "RHODE_ISLAND", "VERMONT"),
                                      MiddleAtlantic = c("DELAWARE", "MARYLAND", "NEW_JERSEY", "NEW_YORK", "PENNSYLVANIA"), 
                                      South = c("ALABAMA", "ARKANSAS", "FLORIDA", "GEORGIA", "KENTUCKY", "LOUISIANA", "MISSISSIPPI", "MISSOURI", "NORTH_CAROLINA", "SOUTH_CAROLINA", "TENNESSEE", "VIRGINIA", "WEST_VIRGINIA"),
                                      Midwest = c("ILLINOIS", "INDIANA", "IOWA", "KANSAS", "MICHIGAN", "MINNESOTA", "NEBRASKA", "NORTH_DAKOTA", "OHIO", "SOUTH_DAKOTA", "WISCONSIN"), 
                                      Southwest = c("ARIZONA", "NEW_MEXICO", "OKLAHOMA", "TEXAS"), 
                                      West = c("ALASKA", "CALIFORNIA", "HAWAII", "IDAHO", "MONTANA", "NEVADA", "OREGON", "UTAH", "WASHINGTON", "WYOMING", "COLORADO"),
                                      Other = c("DISTRICT_OF_COLUMBIA", "DODEA", "NATIONAL")
                                      )

table(states$STATE)
table(states$YEAR)

sum(is.na(states))
sum(!complete.cases(states))
mice::md.pattern(states)
unique(states$STATE)

remove_cols <- c(19,18,17,16,14,13,3)
states1 <- states[,-remove_cols]
mice::md.pattern(states1)
states2 <- states1[complete.cases(states1),]
```

Creating model with complete cases only

```{r}
tune_train_index <- createDataPartition(states2$AVG_READING_4_SCORE, p=.8,
                                   list=F,
                                   times=1)

train <- states2[tune_train_index,]
dim(train)

tune <- states2[-tune_train_index,]
dim(tune)

fitControl <- trainControl(method = "repeatedcv",
                          number = 10,
                          repeats = 5) 

features <- train[,-16]
target <- train$AVG_READING_4_SCORE

set.seed(1999)
myDT <- train(x=features,
                y=target,
                method="rpart2",
                trControl=fitControl,
                metric="RMSE")

plot(myDT)
varImp(myDT)
df_pred <- predict(myDT$finalModel, tune)
df_pred

postResample(df_pred, tune$AVG_READING_4_SCORE)
range(tune$AVG_READING_4_SCORE)
3.75/30

tree.grid <- expand.grid(maxdepth=c(3:20))

myDT1 <- train(x=features,
                y=target,
                method="rpart2",
                trControl=fitControl,
                tuneGrid=tree.grid,
                metric="RMSE")

plot(myDT1)
varImp(myDT1)
df_pred1 <- predict(myDT1$finalModel, tune)
postResample(df_pred1, tune$AVG_READING_4_SCORE)
```

Training on full dataset

```{r}
full.features <- states2[,-16]
full.target <- states2$AVG_READING_4_SCORE

full.myDT <- train(x=full.features,
                y=full.target,
                method="rpart2",
                trControl=fitControl,
                tuneGrid=tree.grid,
                metric="RMSE")
```

Predicting w/ public test dataset

```{r}
test_df <- read.csv('data/test_set_public.csv')
ID <- test_df[,1]
test_df <- test_df[,-1]

test_df$STATE <- fct_collapse(test_df$STATE,
                                      NewEngland = c("CONNECTICUT", "MAINE", "MASSACHUSETTS", "NEW_HAMPSHIRE", "RHODE_ISLAND", "VERMONT"),
                                      MiddleAtlantic = c("DELAWARE", "MARYLAND", "NEW_JERSEY", "NEW_YORK", "PENNSYLVANIA"), 
                                      South = c("ALABAMA", "ARKANSAS", "FLORIDA", "GEORGIA", "KENTUCKY", "LOUISIANA", "MISSISSIPPI", "MISSOURI", "NORTH_CAROLINA", "SOUTH_CAROLINA", "TENNESSEE", "VIRGINIA", "WEST_VIRGINIA"),
                                      Midwest = c("ILLINOIS", "INDIANA", "IOWA", "KANSAS", "MICHIGAN", "MINNESOTA", "NEBRASKA", "NORTH_DAKOTA", "OHIO", "SOUTH_DAKOTA", "WISCONSIN"), 
                                      Southwest = c("ARIZONA", "NEW_MEXICO", "OKLAHOMA", "TEXAS"), 
                                      West = c("ALASKA", "CALIFORNIA", "HAWAII", "IDAHO", "MONTANA", "NEVADA", "OREGON", "UTAH", "WASHINGTON", "WYOMING", "COLORADO"),
                                      Other = c("DISTRICT_OF_COLUMBIA", "DODEA", "NATIONAL")
                                      )

test_pred <- predict(full.myDT$finalModel, test_df)
predictions <- data.frame(ID)
predictions$PREDICTED <- test_pred

write.csv(predictions, 'predictions1.csv', row.names=F)
```
